### ISSUE TITLE
Nomad service is not starting 

### ISSUE THREAD

**Issue by AlbanAndrieu** [pizzamig/minipot#4]
Hi,

Thanks for your work.

I trid you project on TrueNas, and had to :

edit /usr/local/etc/nomad/minipot-server.hcl
# add
data_dir = "/var/tmp/nomad"

So that Nomad will start

**Comment by grembo** [comment]
Hi @AlbanAndrieu, 

Thank you for reporting!

This has been fixed in https://github.com/bsdpot/minipot/commit/8aca6be014f76e77d74406d4392ee7f7db0c1542, but there was no release done for it since. We will do one soon and also update the latest FreeBSD ports tree ~~(but not the 2024Q4 quarterly branch).~~ *Edit: Also will backport to the quarterly branch*

**Comment by grembo** [comment]
Please see:

- https://cgit.freebsd.org/ports/commit/?id=7ce3b964728fc117da072fca58b54a88a0ebb84f
- https://cgit.freebsd.org/ports/commit/?h=2024Q4&id=43ebf1602eb4ce36795e8df806e32477009e307b

Package builders should pick it up soon (not sure when TrueNAS picks it up/if they use FreeBSD package hosts).
